/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.LabRequestDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.daos.PharmacyRequestDaoImplementation;
import info.pkg5100.finalproject.models.LabRequest;
import info.pkg5100.finalproject.models.Patient;
import info.pkg5100.finalproject.models.PharmacyRequest;
import info.pkg5100.finalproject.utils.SimpleTools;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankit
 */
public class HospitalPatientPortal extends javax.swing.JPanel {

    /**
     * Creates new form HospitalPatientPortal
     */
    JPanel mainWorkJPanel;
    Patient currentPatient;
    PatientDaoImplementation patientDaoImplementation;
    LabRequestDaoImplementation labRequestDaoImplementationl;
    PharmacyRequestDaoImplementation pharmacyRequestDaoImplementation;

    public HospitalPatientPortal() {
        initComponents();
    }

    public HospitalPatientPortal(JPanel mainWorkJPanel, Patient currentPatient) {
        initComponents();

        this.mainWorkJPanel = mainWorkJPanel;
        this.currentPatient = currentPatient;

        this.patientDaoImplementation = new PatientDaoImplementation();
        this.labRequestDaoImplementationl = new LabRequestDaoImplementation();
        this.pharmacyRequestDaoImplementation = new PharmacyRequestDaoImplementation();
        populateLabRequestsTable();
        populatePharmacyRequestsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        lblPatientPhone = new javax.swing.JLabel();
        lblPatientStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPharmacyRequest = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLabRequest = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtLabRequest = new javax.swing.JTextField();
        btnCreateLabRequest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPharmacyRequest = new javax.swing.JTextField();
        btnPharmacyRequest = new javax.swing.JButton();

        jLabel1.setText("Patient name:");

        jLabel2.setText("Patient Status:");

        jLabel3.setText("Patient age:");

        jLabel4.setText("Patient phone:");

        lblPatientName.setText("patient_name_placeholder");

        lblPatientAge.setText("patient_age_placeholder");

        lblPatientPhone.setText("patient_phone_placeholder");

        lblPatientStatus.setText("patient_status_placeholder");

        tblPharmacyRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "prescription name", "status"
            }
        ));
        jScrollPane1.setViewportView(tblPharmacyRequest);

        tblLabRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Lab request", "Result", "Request status"
            }
        ));
        jScrollPane2.setViewportView(tblLabRequest);

        jLabel5.setText("Lab request name");

        btnCreateLabRequest.setText("Create lab request");
        btnCreateLabRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLabRequestActionPerformed(evt);
            }
        });

        jLabel6.setText("Prescription :");

        btnPharmacyRequest.setText("Create pharmacy request");
        btnPharmacyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmacyRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(39, 39, 39)
                        .addComponent(lblPatientStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(lblPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(766, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(txtLabRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCreateLabRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel6)
                .addGap(45, 45, 45)
                .addComponent(txtPharmacyRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPharmacyRequest))
            .addGroup(layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPatientName))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblPatientAge))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblPatientPhone))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPatientStatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLabRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateLabRequest))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPharmacyRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPharmacyRequest))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateLabRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLabRequestActionPerformed
        // TODO add your handling code here:
        try {
            int newId = SimpleTools.getUnusedId("labrequests", 1000, 9999);

            LabRequest labRequest = new LabRequest(newId, currentPatient.getId(), "test-requested", txtLabRequest.getText(), "", -1, currentPatient.getLocation(), -1);
            Patient patient = this.patientDaoImplementation.getPatientById(labRequest.getPatientId());
            patient.setLabRequested("true");
            this.patientDaoImplementation.update(patient);
            this.labRequestDaoImplementationl.add(labRequest);

            populateLabRequestsTable();
        } catch (SQLException ex) {
            Logger.getLogger(HospitalPatientPortal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCreateLabRequestActionPerformed

    private void btnPharmacyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmacyRequestActionPerformed
        // TODO add your handling code here:
        try {
            int newId = SimpleTools.getUnusedId("pharmacy", 1000, 9999);

            PharmacyRequest pharmacyRequest = new PharmacyRequest(newId, currentPatient.getId(), txtPharmacyRequest.getText(), "drug-requested", -1, currentPatient.getLocation(), -1, "");
            Patient patient = this.patientDaoImplementation.getPatientById(pharmacyRequest.getPatientId());
            patient.setPharmacyRequested("true");
            this.patientDaoImplementation.update(patient);
            this.pharmacyRequestDaoImplementation.add(pharmacyRequest);

            populatePharmacyRequestsTable();
        } catch (SQLException ex) {
            Logger.getLogger(HospitalPatientPortal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnPharmacyRequestActionPerformed

    void populateLabRequestsTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblLabRequest.getModel();
            model.setRowCount(0);

            for (LabRequest labRequest : this.labRequestDaoImplementationl.getLabRequestsByPatientId(currentPatient.getId())) {
                // -1 means doctor is not assigned yet and is available for picking up by a doctor

                Object[] row = new Object[4];
                row[0] = labRequest;
                row[1] = labRequest.getTestName();
                row[2] = labRequest.getTestResult();
                row[3] = labRequest.getRequestStatus();

                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HospitalPatientPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void populatePharmacyRequestsTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblPharmacyRequest.getModel();
            model.setRowCount(0);

            for (PharmacyRequest pharmacyRequest : this.pharmacyRequestDaoImplementation.getPharmacyRequestsByPatientId(currentPatient.getId())) {
                // -1 means doctor is not assigned yet and is available for picking up by a doctor
                Object[] row = new Object[3];
                row[0] = pharmacyRequest;
                row[1] = pharmacyRequest.getPharmacyRequest();
                row[2] = pharmacyRequest.getStatus();

                model.addRow(row);

            }
        } catch (SQLException ex) {
            Logger.getLogger(HospitalPatientPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateLabRequest;
    private javax.swing.JButton btnPharmacyRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPatientStatus;
    private javax.swing.JTable tblLabRequest;
    private javax.swing.JTable tblPharmacyRequest;
    private javax.swing.JTextField txtLabRequest;
    private javax.swing.JTextField txtPharmacyRequest;
    // End of variables declaration//GEN-END:variables
}
