/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.LabRequestDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.daos.PharmacyRequestDaoImplementation;
import info.pkg5100.finalproject.models.LabRequest;
import info.pkg5100.finalproject.models.Patient;
import info.pkg5100.finalproject.models.PharmacyRequest;
import info.pkg5100.finalproject.utils.SimpleTools;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author ankit
 */
public class HospitalPatientPortal extends javax.swing.JPanel {

	/**
	 * Creates new form HospitalPatientPortal
	 */

    JPanel mainWorkJPanel;
    Patient currentPatient;
    PatientDaoImplementation patientDaoImplementation;
    LabRequestDaoImplementation labRequestDaoImplementationl;
    PharmacyRequestDaoImplementation pharmacyRequestDaoImplementation;

	public HospitalPatientPortal() {
		initComponents();
	}

    public HospitalPatientPortal(JPanel mainWorkJPanel, Patient currentPatient) {
        initComponents();

        mainWorkJPanel = this.mainWorkJPanel;
        currentPatient = this.currentPatient;

        this.patientDaoImplementation = new PatientDaoImplementation();
        this.labRequestDaoImplementationl = new LabRequestDaoImplementation();
        this.pharmacyRequestDaoImplementation = new PharmacyRequestDaoImplementation();
    }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        lblPatientPhone = new javax.swing.JLabel();
        lblPatientStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPharmacyRequest = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLabRequest = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtLabRequest = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPharmacyRequest = new javax.swing.JTextField();
        btnPharmacyRequest = new javax.swing.JButton();

        jLabel1.setText("Patient name:");

        jLabel2.setText("Patient Status:");

        jLabel3.setText("Patient age:");

        jLabel4.setText("Patient phone:");

        lblPatientName.setText("patient_name_placeholder");

        lblPatientAge.setText("patient_age_placeholder");

        lblPatientPhone.setText("patient_phone_placeholder");

        lblPatientStatus.setText("patient_status_placeholder");

        tblPharmacyRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "prescription name", "status"
            }
        ));
        jScrollPane1.setViewportView(tblPharmacyRequest);

        tblLabRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Lab request", "Result", "Request status"
            }
        ));
        jScrollPane2.setViewportView(tblLabRequest);

        jLabel5.setText("Lab request name");

        txtLabRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    txtLabRequestActionPerformed(evt);
                } catch (SQLException e) {
                        e.printStackTrace();
                }
            }
        });

        jButton1.setText("Create lab request");

        jLabel6.setText("Prescription name");

        txtPharmacyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    txtPharmacyRequestActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        btnPharmacyRequest.setText("Create pharmacy request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPharmacyRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPharmacyRequest))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPatientStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(233, 233, 233)
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLabRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jLabel3)
                    .addContainerGap(1231, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jLabel4)
                    .addContainerGap(1217, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblPatientName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtLabRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientAge)
                            .addComponent(jButton1))
                        .addGap(22, 22, 22)
                        .addComponent(lblPatientPhone)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPatientStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(73, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPharmacyRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(btnPharmacyRequest)))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(jLabel3)
                    .addContainerGap(704, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(jLabel4)
                    .addContainerGap(661, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLabRequestActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_txtLabRequestActionPerformed
        // TODO add your handling code here:
        int newId = SimpleTools.getUnusedId("labrequests", 1000, 9999);

        LabRequest labRequest = new LabRequest(newId, this.currentPatient.getId(), "test-requested", txtLabRequest.getText(), "Result not ready", -1);

        this.labRequestDaoImplementationl.add(labRequest);

        populateLabRequestsTable();
    }//GEN-LAST:event_txtLabRequestActionPerformed

    private void txtPharmacyRequestActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_txtPharmacyRequestActionPerformed
        // TODO add your handling code here:
        int newId = SimpleTools.getUnusedId("pharmacy", 1000, 9999);

        PharmacyRequest pharmacyRequest = new PharmacyRequest(newId, this.currentPatient.getId(), txtPharmacyRequest.getText(), "drug-requested", -1);

        this.pharmacyRequestDaoImplementation.add(pharmacyRequest);

        populatePharmacyRequestsTable();
    }//GEN-LAST:event_txtPharmacyRequestActionPerformed

    void populateLabRequestsTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblLabRequest.getModel();
        model.setRowCount(0);

        for(LabRequest labRequest : this.labRequestDaoImplementationl.getLabRequestsByPatientId(this.currentPatient.getId())) {
            // -1 means doctor is not assigned yet and is available for picking up by a doctor

            Object[] row = new Object[4];
            row[0] = labRequest;
            row[1] = labRequest.getTestName();
            row[2] = labRequest.getTestResult();
            row[3] = labRequest.getRequestStatus();

            model.addRow(row);
        }
    }

    void populatePharmacyRequestsTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblPharmacyRequest.getModel();
        model.setRowCount(0);

        for(PharmacyRequest pharmacyRequest : this.pharmacyRequestDaoImplementation.getPharmacyRequestsByPatientId(this.currentPatient.getId())) {
            // -1 means doctor is not assigned yet and is available for picking up by a doctor
            Object[] row = new Object[3];
            row[0] = pharmacyRequest;
            row[1] = pharmacyRequest.getPharmacyRequest();
            row[2] = pharmacyRequest.getStatus();

            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPharmacyRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPatientStatus;
    private javax.swing.JTable tblLabRequest;
    private javax.swing.JTable tblPharmacyRequest;
    private javax.swing.JTextField txtLabRequest;
    private javax.swing.JTextField txtPharmacyRequest;
    // End of variables declaration//GEN-END:variables
}
