/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.models.IncidentHandlingPolice;
import info.pkg5100.finalproject.models.MainSystem;
import info.pkg5100.finalproject.models.Police;

import javax.swing.*;

/**
 *
 * @author hazel
 */
public class IncidentManager extends javax.swing.JPanel {

    /**
     * Creates new form IncidentManager
     */

    MainSystem mainSystem;
    JPanel mainWorkJPanel;
    IncidentHandlingPolice incidentHandlingPolice;
    public IncidentManager() {
        initComponents();
    }

    public IncidentManager(MainSystem mainSystem, JPanel mainWorkJPanel, IncidentHandlingPolice incidentHandlingPolice) {
        initComponents();

        this.mainSystem = mainSystem;
        this.mainWorkJPanel = mainWorkJPanel;
        this.incidentHandlingPolice = incidentHandlingPolice;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportedIncidents = new javax.swing.JTable();
        lblReportIncident = new javax.swing.JLabel();
        btnUpdateIncident = new javax.swing.JButton();
        btnDetailedView = new javax.swing.JButton();

        setForeground(new java.awt.Color(0, 153, 153));

        tblReportedIncidents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Incident Id", "Reporter Name", "Reporter Mobile", "Location", "Description", "Assign"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReportedIncidents);

        lblReportIncident.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblReportIncident.setText("REPORTED INCIDENTS");

        btnUpdateIncident.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdateIncident.setText("Assign");
        btnUpdateIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateIncidentActionPerformed(evt);
            }
        });

        btnDetailedView.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDetailedView.setText("View");
        btnDetailedView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailedViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDetailedView, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnUpdateIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblReportIncident))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblReportIncident)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetailedView, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateIncidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateIncidentActionPerformed

    private void btnDetailedViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailedViewActionPerformed
        // TODO add your handling code here:
        ImpactedPeopleMngt impacted=new ImpactedPeopleMngt();
        
        
    }//GEN-LAST:event_btnDetailedViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailedView;
    private javax.swing.JButton btnUpdateIncident;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReportIncident;
    private javax.swing.JTable tblReportedIncidents;
    // End of variables declaration//GEN-END:variables
}
