/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.models.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author hazel
 */
public class IncidentManager extends javax.swing.JPanel {

    /**
     * Creates new form IncidentManager
     */

    JPanel mainWorkJPanel;
    User incidentHandlingPolice;
    public IncidentManager() {
        initComponents();
    }

    public IncidentManager(JPanel mainWorkJPanel, User incidentHandlingPolice) {
        initComponents();

        this.mainWorkJPanel = mainWorkJPanel;
        this.incidentHandlingPolice = incidentHandlingPolice;

        populateIncidentsTable("Boston");
        populateAmbulanceComboBox("Boston");

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportedIncidents = new javax.swing.JTable();
        lblReportIncident = new javax.swing.JLabel();
        btnAssignInvestigationOfficer = new javax.swing.JButton();
        btnDetailedView = new javax.swing.JButton();
        cmbBoxAmbulanceService = new javax.swing.JComboBox<>();
        cmbBoxInvestigationOfficerList = new javax.swing.JComboBox<>();
        btnAssignAmbulanceService = new javax.swing.JButton();
        lblReportIncident1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCurrentLoggedInIncidentPolice = new javax.swing.JLabel();
        lblCurrentLoggedInIncidentPoliceRole = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 153, 153));

        tblReportedIncidents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Incident Id", "Reporter Name", "Reporter Mobile", "Location", "Description", "Assign"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReportedIncidents);

        lblReportIncident.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblReportIncident.setText("REPORTED INCIDENTS");

        btnAssignInvestigationOfficer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAssignInvestigationOfficer.setText("Assign Investigation officer");
        btnAssignInvestigationOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignInvestigationOfficerActionPerformed(evt);
            }
        });

        btnDetailedView.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDetailedView.setText("View");
        btnDetailedView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailedViewActionPerformed(evt);
            }
        });

        cmbBoxAmbulanceService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbBoxInvestigationOfficerList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAssignAmbulanceService.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAssignAmbulanceService.setText("Assign Ambulance Service");
        btnAssignAmbulanceService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignAmbulanceServiceActionPerformed(evt);
            }
        });

        lblReportIncident1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblReportIncident1.setText("Current logged in User");

        jLabel1.setText("Police name:");

        jLabel2.setText("Role:");

        lblCurrentLoggedInIncidentPolice.setText("police_name_placeolder");

        lblCurrentLoggedInIncidentPoliceRole.setText("police_role_placeolder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDetailedView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbBoxAmbulanceService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbBoxInvestigationOfficerList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAssignInvestigationOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAssignAmbulanceService, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCurrentLoggedInIncidentPoliceRole, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCurrentLoggedInIncidentPolice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReportIncident1)
                            .addComponent(lblReportIncident))))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblReportIncident1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCurrentLoggedInIncidentPolice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCurrentLoggedInIncidentPoliceRole))
                .addGap(126, 126, 126)
                .addComponent(lblReportIncident)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnDetailedView, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxAmbulanceService, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignAmbulanceService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxInvestigationOfficerList, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnAssignInvestigationOfficer, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignInvestigationOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignInvestigationOfficerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignInvestigationOfficerActionPerformed

    private void btnDetailedViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailedViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblReportedIncidents.getSelectedRow();
        if(selectedRowIndex < 0 ) {
            JOptionPane.showMessageDialog(this, "Please select an incident.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblReportedIncidents.getModel();
        IncidentCase incidentCase = (IncidentCase) model.getValueAt(selectedRowIndex, 0);

        IncidentDetailsMngt incidentDetailsMngt = new IncidentDetailsMngt(mainSystem, mainWorkJPanel, incidentCase);
        mainWorkJPanel.add("IncidentDetailsMngt", incidentDetailsMngt);
        CardLayout layout = (CardLayout)mainWorkJPanel.getLayout();
        layout.next(mainWorkJPanel);
    }//GEN-LAST:event_btnDetailedViewActionPerformed

    private void btnAssignAmbulanceServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignAmbulanceServiceActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblReportedIncidents.getSelectedRow();
        if(selectedRowIndex < 0 ) {
            JOptionPane.showMessageDialog(this, "Please select an incident.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblReportedIncidents.getModel();
        IncidentCase incidentCase = (IncidentCase) model.getValueAt(selectedRowIndex, 0);

        String selectedAmbulanceService = cmbBoxAmbulanceService.getSelectedItem().toString();
        for(TransportationOrganization transportationOrganization : this.mainSystem.getTransportationOrganizationList()) {
            for(AmbulanceService ambulanceService : transportationOrganization.getAmbulanceServiceArrayList()) {
                if(ambulanceService.getAmbulanceServiceName().equals(selectedAmbulanceService)) {
                    ambulanceService.getIncidentCaseArrayList().add(incidentCase);
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnAssignAmbulanceServiceActionPerformed

    void populateIncidentsTable(String policeOrganizationNetworkName) {
        DefaultTableModel model = (DefaultTableModel) tblReportedIncidents.getModel();
        model.setRowCount(0);

        for(PoliceOrganization po : this.mainSystem.getMasterPoliceOrganizationList()) {
            if(po.getNetworkName().equals(policeOrganizationNetworkName)) {
                for (IncidentCase incidentCase : po.getIncidentCaseArrayList()) {
                    Object[] row = new Object[6];
                    row[0] = incidentCase;
                    row[1] = incidentCase.getReporter().getReporterName();
                    row[2] = incidentCase.getReporter().getPhone();
                    row[3] = incidentCase.getPoliceStationNetworkName();
                    row[4] = incidentCase.getIncidentDescription();
                    if(incidentCase.getInvestigationPolice() == null) {
                        row[5] = "";
                    } else {
                        row[5] = incidentCase.getInvestigationPolice().getName();
                    }
                    model.addRow(row);
                }
            }
        }
    }

    void populateAmbulanceComboBox(String networkName) {
        for(TransportationOrganization transportationOrganization : this.mainSystem.getTransportationOrganizationList()) {
            if(transportationOrganization.getNetworkName().equals(networkName)) {
                for(AmbulanceService ambulanceService : transportationOrganization.getAmbulanceServiceArrayList()) {
                    cmbBoxAmbulanceService.addItem(ambulanceService.getAmbulanceServiceName());
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignAmbulanceService;
    private javax.swing.JButton btnAssignInvestigationOfficer;
    private javax.swing.JButton btnDetailedView;
    private javax.swing.JComboBox<String> cmbBoxAmbulanceService;
    private javax.swing.JComboBox<String> cmbBoxInvestigationOfficerList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentLoggedInIncidentPolice;
    private javax.swing.JLabel lblCurrentLoggedInIncidentPoliceRole;
    private javax.swing.JLabel lblReportIncident;
    private javax.swing.JLabel lblReportIncident1;
    private javax.swing.JTable tblReportedIncidents;
    // End of variables declaration//GEN-END:variables
}
