/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.LabRequestDaoImplementation;
import info.pkg5100.finalproject.daos.OrganizationDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.models.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankit
 */
public class LabRequestsMngt extends javax.swing.JPanel {

    /**
     * Creates new form LabRequestsMngt
     */
    User currentUser;
    Organization currentOrganization;
    JPanel mainWorkJPanel;

    PatientDaoImplementation patientDaoImplementation;
    OrganizationDaoImplementation organizationDaoImplementation;
    LabRequestDaoImplementation labRequestDaoImplementation;

    public LabRequestsMngt() {
        initComponents();
    }

    public LabRequestsMngt(JPanel mainWorkJPanel, User currentUser, Organization currentOrganization) {
        initComponents();

        this.mainWorkJPanel = mainWorkJPanel;
        this.currentUser = currentUser;
        this.currentOrganization = currentOrganization;

        this.patientDaoImplementation = new PatientDaoImplementation();
        this.organizationDaoImplementation = new OrganizationDaoImplementation();
        this.labRequestDaoImplementation = new LabRequestDaoImplementation();
        lblLabTechId.setText(String.valueOf(currentUser.getId()));
        lblLabTechName.setText(currentUser.getName());
        lblLabTechPhone.setText(currentUser.getPhone());
        
        
        
        populateAvailableLabRequests();
        populateAcceptedLabRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLabTechName = new javax.swing.JLabel();
        lblLabTechPhone = new javax.swing.JLabel();
        lblLabTechId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAcceptedLabRequests = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvailableLabRequests = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTestResult = new javax.swing.JTextField();
        btnAcceptLab = new javax.swing.JButton();
        btnAcceptLab1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lab technician name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Lab tech phone:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("lab tech id:");

        lblLabTechName.setText("lab_technician_name_placeholder");

        lblLabTechPhone.setText("lab_technician_phone_placeholder");

        lblLabTechId.setText("lab_technician_id_placeholder");

        tblAcceptedLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Lab request", "Result", "Status", "Patient Id"
            }
        ));
        jScrollPane2.setViewportView(tblAcceptedLabRequests);

        tblAvailableLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Lab request", "Result", "Status", "Patient Id"
            }
        ));
        jScrollPane3.setViewportView(tblAvailableLabRequests);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pending lab requests");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Accepted lab requests");

        jLabel6.setBackground(new java.awt.Color(31, 75, 124));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lab Request Management");
        jLabel6.setOpaque(true);

        btnAcceptLab.setBackground(new java.awt.Color(31, 75, 124));
        btnAcceptLab.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceptLab.setText("Accept Lab Request");
        btnAcceptLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptLabActionPerformed(evt);
            }
        });

        btnAcceptLab1.setBackground(new java.awt.Color(31, 75, 124));
        btnAcceptLab1.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceptLab1.setText("Update test result");
        btnAcceptLab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptLab1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(txtTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnAcceptLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnAcceptLab, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLabTechId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblLabTechName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLabTechPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblLabTechId))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblLabTechName))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblLabTechPhone))))
                .addGap(18, 18, 18)
                .addComponent(btnAcceptLab)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcceptLab1))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptLabActionPerformed
       
        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAvailableLabRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a record.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAvailableLabRequests.getModel();
            LabRequest labRequest = (LabRequest) model.getValueAt(selectedRowIndex, 0);

            
            
            labRequest.setEmployeeid(this.currentUser.getId());
            labRequest.setRequestStatus("test-in-progress");
            this.labRequestDaoImplementation.update(labRequest);
            populateAvailableLabRequests();
            populateAcceptedLabRequests();

        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAcceptLabActionPerformed

    private void btnAcceptLab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptLab1ActionPerformed
        // TODO add your handling code here:
        
        try {
            
            if(txtTestResult.getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this, "Please fill Test Result.");
                return;
            }
            
            int selectedRowIndex = tblAcceptedLabRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a record.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAcceptedLabRequests.getModel();
            LabRequest labRequest = (LabRequest) model.getValueAt(selectedRowIndex, 0);
            
            labRequest.setRequestStatus("test-done");
            labRequest.setTestResult(txtTestResult.getText());
            this.labRequestDaoImplementation.update(labRequest);
            populateAvailableLabRequests();
            populateAcceptedLabRequests();
            
            txtTestResult.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAcceptLab1ActionPerformed

    void populateAvailableLabRequests() {
        DefaultTableModel model = (DefaultTableModel) tblAvailableLabRequests.getModel();
        model.setRowCount(0);
        try {
            for (LabRequest labRequest : this.labRequestDaoImplementation.getLabRequestsByStatus("test-requested")) {

                if (labRequest.getNetwork().equals(this.currentOrganization.getLocation())) {
                    Object[] row = new Object[5];
                    row[0] = labRequest;
                    row[1] = labRequest.getTestName();
                    row[2] = labRequest.getTestResult();
                    row[3] = labRequest.getRequestStatus();
                    row[4] = labRequest.getPatientId();
                  

                    model.addRow(row);
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void populateAcceptedLabRequests() {
        DefaultTableModel model = (DefaultTableModel) tblAcceptedLabRequests.getModel();
        model.setRowCount(0);
        try {
            for (LabRequest labRequest : this.labRequestDaoImplementation.getLabRequestByEmployeeId(this.currentUser.getId())) {
                
                if ("test-in-progress".equals(labRequest.getRequestStatus())) {
                    Object[] row = new Object[5];
                    row[0] = labRequest;
                    row[1] = labRequest.getTestName();
                    row[2] = labRequest.getTestResult();
                    row[3] = labRequest.getRequestStatus();
                    row[4] = labRequest.getPatientId();
                    

                    model.addRow(row);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptLab;
    private javax.swing.JButton btnAcceptLab1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLabTechId;
    private javax.swing.JLabel lblLabTechName;
    private javax.swing.JLabel lblLabTechPhone;
    private javax.swing.JTable tblAcceptedLabRequests;
    private javax.swing.JTable tblAvailableLabRequests;
    private javax.swing.JTextField txtTestResult;
    // End of variables declaration//GEN-END:variables
}
