/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.LabRequestDaoImplementation;
import info.pkg5100.finalproject.daos.OrganizationDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.models.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankit
 */
public class LabRequestsMngt extends javax.swing.JPanel {

    /**
     * Creates new form LabRequestsMngt
     */
    User currentUser;
    Organization currentOrganization;
    JPanel mainWorkJPanel;

    PatientDaoImplementation patientDaoImplementation;
    OrganizationDaoImplementation organizationDaoImplementation;
    LabRequestDaoImplementation labRequestDaoImplementation;

    public LabRequestsMngt() {
        initComponents();
    }

    public LabRequestsMngt(JPanel mainWorkJPanel, User currentUser, Organization currentOrganization) {
        initComponents();

        this.mainWorkJPanel = mainWorkJPanel;
        this.currentUser = currentUser;
        this.currentOrganization = currentOrganization;

        this.patientDaoImplementation = new PatientDaoImplementation();
        this.organizationDaoImplementation = new OrganizationDaoImplementation();
        this.labRequestDaoImplementation = new LabRequestDaoImplementation();

        populateAvailableLabRequests();
        populateAcceptedLabRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLabTechName = new javax.swing.JLabel();
        lblLabTechPhone = new javax.swing.JLabel();
        lblLabTechId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAcceptedLabRequests = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvailableLabRequests = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAcceptLabRequest = new javax.swing.JButton();
        btnUpdateTestResult = new javax.swing.JButton();
        btnCompleteRequest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTestResult = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lab technician name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Lab tech phone:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("lab tech id:");

        lblLabTechName.setText("lab_technician_name_placeholder");

        lblLabTechPhone.setText("lab_technician_phone_placeholder");

        lblLabTechId.setText("lab_technician_id_placeholder");

        tblAcceptedLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Lab request", "Result", "status", "Patient Id"
            }
        ));
        jScrollPane2.setViewportView(tblAcceptedLabRequests);

        tblAvailableLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Lab request", "Result", "status", "Patient Id"
            }
        ));
        jScrollPane3.setViewportView(tblAvailableLabRequests);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pending lab requests");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Accepted lab requests");

        btnAcceptLabRequest.setText("Accept lab request");
        btnAcceptLabRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptLabRequestActionPerformed(evt);
            }
        });

        btnUpdateTestResult.setText("Update test result");
        btnUpdateTestResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTestResultActionPerformed(evt);
            }
        });

        btnCompleteRequest.setText("Complete request");

        jLabel6.setBackground(new java.awt.Color(31, 75, 124));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lab Request Management");
        jLabel6.setOpaque(true);

        txtTestResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTestResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnUpdateTestResult)
                        .addGap(45, 45, 45)
                        .addComponent(btnCompleteRequest)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLabTechId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblLabTechName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLabTechPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(jLabel4)))))
                .addGap(0, 186, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAcceptLabRequest)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblLabTechId))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblLabTechName))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblLabTechPhone))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAcceptLabRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTestResult)
                    .addComponent(btnCompleteRequest)
                    .addComponent(txtTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptLabRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptLabRequestActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAvailableLabRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a record.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAvailableLabRequests.getModel();
            LabRequest labRequest = (LabRequest) model.getValueAt(selectedRowIndex, 0);

            
            
            labRequest.setEmployeeid(this.currentUser.getId());
            labRequest.setRequestStatus("test-in-progress");
            this.labRequestDaoImplementation.update(labRequest);
            populateAvailableLabRequests();
            populateAcceptedLabRequests();

        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnAcceptLabRequestActionPerformed

    private void btnUpdateTestResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTestResultActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAcceptedLabRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a record.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAcceptedLabRequests.getModel();
            LabRequest labRequest = (LabRequest) model.getValueAt(selectedRowIndex, 0);
            
            labRequest.setRequestStatus("test-done");
            labRequest.setTestResult(txtTestResult.getText());
            this.labRequestDaoImplementation.update(labRequest);
            populateAvailableLabRequests();
            populateAcceptedLabRequests();

        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnUpdateTestResultActionPerformed

    private void txtTestResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTestResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestResultActionPerformed

    void populateAvailableLabRequests() {
        DefaultTableModel model = (DefaultTableModel) tblAvailableLabRequests.getModel();
        model.setRowCount(0);
        try {
            for (LabRequest labRequest : this.labRequestDaoImplementation.getLabRequestsByStatus("test-requested")) {

                if (labRequest.getNetwork().equals(this.currentOrganization.getLocation())) {
                    Object[] row = new Object[5];
                    row[0] = labRequest;
                    row[1] = labRequest.getTestName();
                    row[2] = labRequest.getTestResult();
                    row[3] = labRequest.getRequestStatus();
                    row[4] = labRequest.getPatientId();
                  

                    model.addRow(row);
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void populateAcceptedLabRequests() {
        DefaultTableModel model = (DefaultTableModel) tblAcceptedLabRequests.getModel();
        model.setRowCount(0);
        try {
            for (LabRequest labRequest : this.labRequestDaoImplementation.getLabRequestByEmployeeId(this.currentUser.getId())) {
                // -1 means doctor is not assigned yet and is available for picking up by a doctor
                if ("test-in-progress".equals(labRequest.getRequestStatus())) {
                    Object[] row = new Object[5];
                    row[0] = labRequest;
                    row[1] = labRequest.getTestName();
                    row[2] = labRequest.getTestResult();
                    row[3] = labRequest.getRequestStatus();
                    row[4] = labRequest.getPatientId();
                    

                    model.addRow(row);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LabRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptLabRequest;
    private javax.swing.JButton btnCompleteRequest;
    private javax.swing.JButton btnUpdateTestResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLabTechId;
    private javax.swing.JLabel lblLabTechName;
    private javax.swing.JLabel lblLabTechPhone;
    private javax.swing.JTable tblAcceptedLabRequests;
    private javax.swing.JTable tblAvailableLabRequests;
    private javax.swing.JTextField txtTestResult;
    // End of variables declaration//GEN-END:variables
}
