/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.LabRequestDaoImplementation;
import info.pkg5100.finalproject.daos.OrganizationDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.models.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author ankit
 */
public class LabRequestsMngt extends javax.swing.JPanel {

	/**
	 * Creates new form LabRequestsMngt
	 */

    User currentUser;
    Organization currentOrganization;
    JPanel mainWorkJPanel;

    PatientDaoImplementation patientDaoImplementation;
    OrganizationDaoImplementation organizationDaoImplementation;
    LabRequestDaoImplementation labRequestDaoImplementation;

	public LabRequestsMngt() {
		initComponents();
	}

    public LabRequestsMngt(JPanel mainWorkJPanel, User currentUser, Organization currentOrganization) {
        initComponents();

        this.mainWorkJPanel = mainWorkJPanel;
        this.currentUser = currentUser;
        this.currentOrganization = currentOrganization;

        this.patientDaoImplementation = new PatientDaoImplementation();
        this.organizationDaoImplementation = new OrganizationDaoImplementation();
        this.labRequestDaoImplementation = new LabRequestDaoImplementation();
    }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLabTechName = new javax.swing.JLabel();
        lblLabTechPhone = new javax.swing.JLabel();
        lblLabTechId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAcceptedLabRequests = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvailableLabRequests = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAcceptLabRequest = new javax.swing.JButton();
        btnUpdateTestResult = new javax.swing.JButton();
        txtTestResult = new javax.swing.JTextField();
        btnCompleteRequest = new javax.swing.JButton();

        jLabel1.setText("Lab technician name:");

        jLabel2.setText("lab tech phone:");

        jLabel3.setText("lab tech id:");

        lblLabTechName.setText("lab_technician_name_placeholder");

        lblLabTechPhone.setText("lab_technician_phone_placeholder");

        lblLabTechId.setText("lab_technician_id_placeholder");

        tblAcceptedLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Lab request", "Result", "status", "Patient Name"
            }
        ));
        jScrollPane2.setViewportView(tblAcceptedLabRequests);

        tblAvailableLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Lab request", "Result", "status", "Patient Name"
            }
        ));
        jScrollPane3.setViewportView(tblAvailableLabRequests);

        jLabel4.setText("Available lab requests");

        jLabel5.setText("Accepted lab requests");

        btnAcceptLabRequest.setText("Accept lab request");

        btnUpdateTestResult.setText("Update test result");

        txtTestResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTestResultActionPerformed(evt);
            }
        });

        btnCompleteRequest.setText("Complete request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLabTechId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblLabTechName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLabTechPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnAcceptLabRequest))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnUpdateTestResult)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnCompleteRequest))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel5)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblLabTechName))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblLabTechPhone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblLabTechId))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcceptLabRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateTestResult)
                            .addComponent(txtTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(btnCompleteRequest)
                        .addGap(31, 31, 31)))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTestResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTestResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestResultActionPerformed


    void populateAvailableLabRequests() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblAvailableLabRequests.getModel();
        model.setRowCount(0);

        for(LabRequest labRequest : this.labRequestDaoImplementation.getLabRequestsByStatus("test-requested")) {
            int patientId = labRequest.getPatientId();
            Patient patient = this.patientDaoImplementation.getPatientById(patientId);

            int hospitalId = patient.getHospitalId();
            Organization hospital = this.organizationDaoImplementation.getOrganizationById(hospitalId);

            if(hospital.getLocation().equals(this.currentOrganization.getLocation())) {
                Object[] row = new Object[3];
                row[0] = labRequest;
                row[1] = labRequest.getPharmacyRequest();
                row[2] = pharmalabRequestcyRequest.getStatus();

                model.addRow(row);
            }

        }
    }

    void populateAcceptedLabRequests() {
        DefaultTableModel model = (DefaultTableModel) tblAcceptedLabRequests.getModel();
        model.setRowCount(0);

        for(LabRequest labRequest : this.labRequestDaoImplementation.getPharmacyRequestsByPatientId(this.currentPatient.getId())) {
            // -1 means doctor is not assigned yet and is available for picking up by a doctor
            Object[] row = new Object[3];
            row[0] = labRequest;
            row[1] = labRequest.getPharmacyRequest();
            row[2] = labRequest.getStatus();

            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptLabRequest;
    private javax.swing.JButton btnCompleteRequest;
    private javax.swing.JButton btnUpdateTestResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLabTechId;
    private javax.swing.JLabel lblLabTechName;
    private javax.swing.JLabel lblLabTechPhone;
    private javax.swing.JTable tblAcceptedLabRequests;
    private javax.swing.JTable tblAvailableLabRequests;
    private javax.swing.JTextField txtTestResult;
    // End of variables declaration//GEN-END:variables
}
