/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.NetworkDaoImplementation;
import info.pkg5100.finalproject.models.Network;
import info.pkg5100.finalproject.utils.SimpleTools;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hazel
 */
public class NetworkMngt extends javax.swing.JPanel {

    /**
     * Creates new form NetworkMngt
     */
    JPanel mainWorkJPanel;
    NetworkDaoImplementation networkDaoImplementation;
    public NetworkMngt() {
        initComponents();
        this.networkDaoImplementation=new NetworkDaoImplementation();
        
    }

    
    public NetworkMngt(JPanel mainWorkJPanel) {
        initComponents();
         this.networkDaoImplementation=new NetworkDaoImplementation();
        this.mainWorkJPanel=mainWorkJPanel;
        try {
            populateNetworksTable(this.networkDaoImplementation.getNetworks());
        } catch (SQLException ex) {
            Logger.getLogger(NetworkMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNetworkName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCreateNetwork = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetworkList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCreateNetwork1 = new javax.swing.JButton();

        txtNetworkName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetworkNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Add Nework");

        btnCreateNetwork.setText("Create Network");
        btnCreateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetworkActionPerformed(evt);
            }
        });

        tblNetworkList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "name"
            }
        ));
        jScrollPane1.setViewportView(tblNetworkList);

        jLabel1.setText("Network Name");

        jLabel4.setText("Available Network");

        btnCreateNetwork1.setText("Create Enterprise");
        btnCreateNetwork1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetwork1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(234, 234, 234))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(89, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnCreateNetwork)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateNetwork1)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addComponent(btnCreateNetwork))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnCreateNetwork1)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNetworkNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetworkNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetworkNameActionPerformed

    private void btnCreateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetworkActionPerformed
        try {                                                 
            int newId=-1;
           
                // TODO add your handling code here:
            newId=SimpleTools.getUnusedId("networks", 1000, 9999);
            Network network = new Network(newId, txtNetworkName.getText());
            this.networkDaoImplementation.add(network);
            
            populateNetworksTable(this.networkDaoImplementation.getNetworks());
        } catch (SQLException ex) {
            Logger.getLogger(NetworkMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateNetworkActionPerformed

    private void btnCreateNetwork1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetwork1ActionPerformed
        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblNetworkList.getSelectedRow();
            if(selectedRowIndex < 0 ) {
                JOptionPane.showMessageDialog(this, "Please select a Network record to View");
                return;
            }
            
            DefaultTableModel model = (DefaultTableModel) tblNetworkList.getModel();
            Network selectedNetwork = (Network) model.getValueAt(selectedRowIndex, 0);
            
            EnterpriseMngt enterpriseMngt = new EnterpriseMngt(mainWorkJPanel,selectedNetwork);
            mainWorkJPanel.add("EnterpriseMngt",enterpriseMngt);
            CardLayout layout = (CardLayout)mainWorkJPanel.getLayout();
            layout.next(mainWorkJPanel);
        } catch (SQLException ex) {
            Logger.getLogger(NetworkMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateNetwork1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNetwork;
    private javax.swing.JButton btnCreateNetwork1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNetworkList;
    private javax.swing.JTextField txtNetworkName;
    // End of variables declaration//GEN-END:variables

    private void populateNetworksTable(List<Network> networks) {
        DefaultTableModel model = (DefaultTableModel) tblNetworkList.getModel();
        model.setRowCount(0);
        for (Network network : networks) {
            Object[] row = new Object[4];
            row[0] = network;
            row[1] = network.getNetworkName();
            model.addRow(row);
        }
    }
}
