/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.IncidenteCaseDaoImplementation;
import info.pkg5100.finalproject.daos.OrganizationDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.daos.UserDaoImplementation;
import info.pkg5100.finalproject.models.Organization;
import info.pkg5100.finalproject.models.Patient;
import info.pkg5100.finalproject.models.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankit
 */
public class PatientHousingRequestMngt extends javax.swing.JPanel {

    /**
     * Creates new form HospitalIncidentManager
     */
    JPanel mainWorkJPanel;
    User currentuser;
    Organization currentOrganization;

    UserDaoImplementation userDaoImplementation;
    OrganizationDaoImplementation organizationDaoImplementation;
    IncidenteCaseDaoImplementation incidenteCaseDaoImplementation;
    PatientDaoImplementation patientDaoImplementation;

    public PatientHousingRequestMngt() {
        initComponents();
    }

    public PatientHousingRequestMngt(JPanel mainWorkJPanel, User currentuser, Organization currentOrganization) throws SQLException {
        initComponents();

        this.currentOrganization = currentOrganization;
        this.currentuser = currentuser;
        this.mainWorkJPanel = mainWorkJPanel;

        this.userDaoImplementation = new UserDaoImplementation();
        this.organizationDaoImplementation = new OrganizationDaoImplementation();
        this.incidenteCaseDaoImplementation = new IncidenteCaseDaoImplementation();
        this.patientDaoImplementation = new PatientDaoImplementation();

        jcbHousindDays.removeAllItems();
        jcbHousindDays.addItem("20");
        jcbHousindDays.addItem("30");
        jcbHousindDays.addItem("40");
        jcbHousindDays.addItem("50");
        populateRequestsTable();
        populateAcceptedCaseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcceptedPatients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvailablePatient = new javax.swing.JTable();
        btnAcceptRequest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbHousindDays = new javax.swing.JComboBox<>();
        lblHousingDays = new javax.swing.JLabel();
        btnRemoveFromHousing = new javax.swing.JButton();
        btnDoctorsComment = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblAcceptedPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Housing For Days", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblAcceptedPatients);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Requested Patients");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Accepted Patients");

        tblAvailablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Police Report", "Incident Case"
            }
        ));
        jScrollPane3.setViewportView(tblAvailablePatient);

        btnAcceptRequest.setBackground(new java.awt.Color(31, 75, 124));
        btnAcceptRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceptRequest.setText("Accept");
        btnAcceptRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptRequestActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(31, 75, 124));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Housing Management");
        jLabel6.setOpaque(true);

        jcbHousindDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHousingDays.setText("Housing For Days :");

        btnRemoveFromHousing.setBackground(new java.awt.Color(31, 75, 124));
        btnRemoveFromHousing.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveFromHousing.setText("Remove Housing");
        btnRemoveFromHousing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromHousingActionPerformed(evt);
            }
        });

        btnDoctorsComment.setBackground(new java.awt.Color(31, 75, 124));
        btnDoctorsComment.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctorsComment.setText("Doctor's Comment");
        btnDoctorsComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorsCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHousingDays)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbHousindDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAcceptRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDoctorsComment)))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(btnRemoveFromHousing, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHousingDays)
                    .addComponent(jcbHousindDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcceptRequest)
                    .addComponent(btnDoctorsComment))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnRemoveFromHousing)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptRequestActionPerformed
        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAvailablePatient.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Patient.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAvailablePatient.getModel();
            Patient patient = (Patient) model.getValueAt(selectedRowIndex, 0);

            //incidentCase.setOrgId(this.currentOrganization.getId());
            //incidentCase.setOrgType(this.currentOrganization.getType());
            patient.setHousingid(this.currentuser.getId());
            patient.setHousingPeriod(Integer.valueOf(jcbHousindDays.getSelectedItem().toString()));

            this.patientDaoImplementation.update(patient);
            populateAcceptedCaseTable();
            populateRequestsTable();

        } catch (SQLException ex) {
            Logger.getLogger(PatientHousingRequestMngt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAcceptRequestActionPerformed

    private void btnRemoveFromHousingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromHousingActionPerformed
        // TODO add your handling code here:
        try {
            
            int selectedRowIndex = tblAcceptedPatients.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Patient.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAcceptedPatients.getModel();
            Patient patient = (Patient) model.getValueAt(selectedRowIndex, 0);

            //incidentCase.setOrgId(this.currentOrganization.getId());
            //incidentCase.setOrgType(this.currentOrganization.getType());
            patient.setHousingid(-1);
            patient.setHousingPeriod(-1);

            this.patientDaoImplementation.update(patient);
            populateAcceptedCaseTable();
            populateRequestsTable();

        } catch (SQLException ex) {
            Logger.getLogger(PatientHousingRequestMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveFromHousingActionPerformed

    private void btnDoctorsCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsCommentActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAvailablePatient.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Patient.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAvailablePatient.getModel();
            Patient patient = (Patient) model.getValueAt(selectedRowIndex, 0);

            
            
            String doctorComment = this.patientDaoImplementation.getPatientById(patient.getId()).getPatientIssue();
            JOptionPane.showMessageDialog(this, doctorComment);

        } catch (SQLException ex) {
            Logger.getLogger(PatientHousingRequestMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnDoctorsCommentActionPerformed

    void populateAcceptedCaseTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblAcceptedPatients.getModel();
        model.setRowCount(0);

        for (Patient patient : this.patientDaoImplementation.getPatientsByLocationAndConvicted(currentOrganization.getLocation(), "Innocent")) {

            if (patient.getHousingid() == this.currentuser.getId() && patient.getHousingPeriod() > -1) {
                Object[] row = new Object[4];
                row[0] = patient;
                row[1] = patient.getName();
                row[2] = patient.getHousingPeriod();
                row[3] = patient.getIsConvicted();

                model.addRow(row);
            }
        }
    }

    void populateRequestsTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblAvailablePatient.getModel();
        model.setRowCount(0);

        for (Patient patient : this.patientDaoImplementation.getPatientsByLocationAndConvicted(currentOrganization.getLocation(), "Innocent")) {

            if (patient.getHousingPeriod() < 0) {
                Object[] row = new Object[4];
                row[0] = patient;
                row[1] = patient.getName();
                row[2] = patient.getIsConvicted();
                row[3] = patient.getIncidentCaseId();

                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptRequest;
    private javax.swing.JButton btnDoctorsComment;
    private javax.swing.JButton btnRemoveFromHousing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbHousindDays;
    private javax.swing.JLabel lblHousingDays;
    private javax.swing.JTable tblAcceptedPatients;
    private javax.swing.JTable tblAvailablePatient;
    // End of variables declaration//GEN-END:variables
}
