/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.IncidenteCaseDaoImplementation;
import info.pkg5100.finalproject.daos.OrganizationDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.daos.UserDaoImplementation;
import info.pkg5100.finalproject.models.Organization;
import info.pkg5100.finalproject.models.Patient;
import info.pkg5100.finalproject.models.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankit
 */
public class PatientDetentionRequestMngt extends javax.swing.JPanel {

    /**
     * Creates new form HospitalIncidentManager
     */
    JPanel mainWorkJPanel;
    User currentuser;
    Organization currentOrganization;

    UserDaoImplementation userDaoImplementation;
    OrganizationDaoImplementation organizationDaoImplementation;
    IncidenteCaseDaoImplementation incidenteCaseDaoImplementation;
    PatientDaoImplementation patientDaoImplementation;

    public PatientDetentionRequestMngt() {
        initComponents();
    }

    public PatientDetentionRequestMngt(JPanel mainWorkJPanel, User currentuser, Organization currentOrganization) throws SQLException {
        initComponents();

        this.currentOrganization = currentOrganization;
        this.currentuser = currentuser;
        this.mainWorkJPanel = mainWorkJPanel;

        this.userDaoImplementation = new UserDaoImplementation();
        this.organizationDaoImplementation = new OrganizationDaoImplementation();
        this.incidenteCaseDaoImplementation = new IncidenteCaseDaoImplementation();
        this.patientDaoImplementation = new PatientDaoImplementation();

        jcbDetentionDays.removeAllItems();
        jcbDetentionDays.addItem("20");
        jcbDetentionDays.addItem("30");
        jcbDetentionDays.addItem("40");
        jcbDetentionDays.addItem("50");
        populateRequestsTable();
        populateAcceptedCaseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcceptedPatients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvailablePatient = new javax.swing.JTable();
        btnAcceptRequest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbDetentionDays = new javax.swing.JComboBox<>();
        lblDetentionDays = new javax.swing.JLabel();
        btnRemoveFromDetention = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblAcceptedPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Detention For Days", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblAcceptedPatients);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Requested Patients");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Accepted Patients");

        tblAvailablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Police Report", "Incident Case"
            }
        ));
        jScrollPane3.setViewportView(tblAvailablePatient);

        btnAcceptRequest.setBackground(new java.awt.Color(31, 75, 124));
        btnAcceptRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceptRequest.setText("Accept");
        btnAcceptRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptRequestActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(31, 75, 124));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Detention Management");
        jLabel6.setOpaque(true);

        jcbDetentionDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDetentionDays.setText("Detention For Days :");

        btnRemoveFromDetention.setBackground(new java.awt.Color(31, 75, 124));
        btnRemoveFromDetention.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveFromDetention.setText("Remove");
        btnRemoveFromDetention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromDetentionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblDetentionDays)
                        .addGap(78, 78, 78)
                        .addComponent(jcbDetentionDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(btnAcceptRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 268, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(btnRemoveFromDetention, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetentionDays)
                    .addComponent(jcbDetentionDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcceptRequest))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btnRemoveFromDetention)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptRequestActionPerformed
        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAvailablePatient.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select an incident.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAvailablePatient.getModel();
            Patient patient = (Patient) model.getValueAt(selectedRowIndex, 0);

            //incidentCase.setOrgId(this.currentOrganization.getId());
            //incidentCase.setOrgType(this.currentOrganization.getType());
            patient.setDetentionid(this.currentuser.getId());
            patient.setDetentionPeriod(Integer.valueOf(jcbDetentionDays.getSelectedItem().toString()));

            this.patientDaoImplementation.update(patient);
            populateAcceptedCaseTable();
            populateRequestsTable();

        } catch (SQLException ex) {
            Logger.getLogger(PatientDetentionRequestMngt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAcceptRequestActionPerformed

    private void btnRemoveFromDetentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromDetentionActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAcceptedPatients.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select an incident.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAcceptedPatients.getModel();
            Patient patient = (Patient) model.getValueAt(selectedRowIndex, 0);

            //incidentCase.setOrgId(this.currentOrganization.getId());
            //incidentCase.setOrgType(this.currentOrganization.getType());
            patient.setDetentionid(-1);
            patient.setDetentionPeriod(-1);

            this.patientDaoImplementation.update(patient);
            populateAcceptedCaseTable();
            populateRequestsTable();

        } catch (SQLException ex) {
            Logger.getLogger(PatientDetentionRequestMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveFromDetentionActionPerformed

    void populateAcceptedCaseTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblAcceptedPatients.getModel();
        model.setRowCount(0);

        for (Patient patient : this.patientDaoImplementation.getPatientsByLocationAndConvicted(currentOrganization.getLocation(), "Convict")) {

            if (patient.getDetentionid()== this.currentuser.getId() && patient.getDetentionPeriod()> -1) {
                Object[] row = new Object[4];
                row[0] = patient;
                row[1] = patient.getName();
                row[2] = patient.getDetentionPeriod();
                row[3] = patient.getIsConvicted();

                model.addRow(row);
            }
        }
    }

    void populateRequestsTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblAvailablePatient.getModel();
        model.setRowCount(0);

        for (Patient patient : this.patientDaoImplementation.getPatientsByLocationAndConvicted(currentOrganization.getLocation(), "Convict")) {

            if (patient.getDetentionPeriod()< 0) {
                Object[] row = new Object[4];
                row[0] = patient;
                row[1] = patient.getName();
                row[2] = patient.getIsConvicted();
                row[3] = patient.getIncidentCaseId();

                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptRequest;
    private javax.swing.JButton btnRemoveFromDetention;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbDetentionDays;
    private javax.swing.JLabel lblDetentionDays;
    private javax.swing.JTable tblAcceptedPatients;
    private javax.swing.JTable tblAvailablePatient;
    // End of variables declaration//GEN-END:variables
}
