/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info.pkg5100.finalproject.ui;

import info.pkg5100.finalproject.daos.OrganizationDaoImplementation;
import info.pkg5100.finalproject.daos.PatientDaoImplementation;
import info.pkg5100.finalproject.daos.PharmacyRequestDaoImplementation;
import info.pkg5100.finalproject.models.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gaurav
 */
public class PharmacyRequestsMngt extends javax.swing.JPanel {

    /**
     * Creates new form LabRequestsMngt
     */
    User currentUser;
    Organization currentOrganization;
    JPanel mainWorkJPanel;

    PatientDaoImplementation patientDaoImplementation;
    OrganizationDaoImplementation organizationDaoImplementation;
    PharmacyRequestDaoImplementation pharmacyRequestDaoImplementation;

    public PharmacyRequestsMngt() {
        initComponents();
    }

    public PharmacyRequestsMngt(JPanel mainWorkJPanel, User currentUser, Organization currentOrganization) {
        initComponents();

        this.mainWorkJPanel = mainWorkJPanel;
        this.currentUser = currentUser;
        this.currentOrganization = currentOrganization;

        this.patientDaoImplementation = new PatientDaoImplementation();
        this.organizationDaoImplementation = new OrganizationDaoImplementation();
        this.pharmacyRequestDaoImplementation = new PharmacyRequestDaoImplementation();

        populateAvailablePharmacyRequests();
        populateAcceptedPharmacyRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPharmacyEmployeeName = new javax.swing.JLabel();
        lblPharmacyEmployeePhone = new javax.swing.JLabel();
        lblPharmacyEmployeeId = new javax.swing.JLabel();
        lblPharmEmpName = new javax.swing.JLabel();
        lblPharmEmpPhone = new javax.swing.JLabel();
        lblPharmEmpId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAcceptedPharmRequests = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvailablePharmRequests = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAcceptPharmRequest = new javax.swing.JButton();
        btnUpdatePharmRequest = new javax.swing.JButton();
        txtPharmResult = new javax.swing.JTextField();
        btnCompleteRequest = new javax.swing.JButton();

        lblPharmacyEmployeeName.setText("Pharmacy Employee Name :");

        lblPharmacyEmployeePhone.setText("Pharmacy Emp Phone :");

        lblPharmacyEmployeeId.setText("Pharmacy Employee Id :");

        lblPharmEmpName.setText("pharmacyemp_name_placeholder");

        lblPharmEmpPhone.setText("pharmacyemp_phone_placeholder");

        lblPharmEmpId.setText("pharmacyemp_id_placeholder");

        tblAcceptedPharmRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Pharm request", "Response", "status", "Patient Id"
            }
        ));
        jScrollPane2.setViewportView(tblAcceptedPharmRequests);

        tblAvailablePharmRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Pharm request", "Response", "status", "Patient Id"
            }
        ));
        jScrollPane3.setViewportView(tblAvailablePharmRequests);

        jLabel4.setText("Available Pharmacy requests");

        jLabel5.setText("Accepted Pharmacy Requests");

        btnAcceptPharmRequest.setText("Accept lab request");
        btnAcceptPharmRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptPharmRequestActionPerformed(evt);
            }
        });

        btnUpdatePharmRequest.setText("Update test result");
        btnUpdatePharmRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePharmRequestActionPerformed(evt);
            }
        });

        txtPharmResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmResultActionPerformed(evt);
            }
        });

        btnCompleteRequest.setText("Complete request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPharmacyEmployeeName)
                                    .addComponent(lblPharmacyEmployeePhone)
                                    .addComponent(lblPharmacyEmployeeId))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPharmEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblPharmEmpName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPharmEmpPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAcceptPharmRequest)
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(txtPharmResult, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnUpdatePharmRequest)
                        .addGap(74, 74, 74)
                        .addComponent(btnCompleteRequest)))
                .addGap(0, 120, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPharmacyEmployeeName)
                    .addComponent(lblPharmEmpName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPharmacyEmployeePhone)
                    .addComponent(lblPharmEmpPhone))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPharmacyEmployeeId)
                    .addComponent(lblPharmEmpId))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAcceptPharmRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPharmResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePharmRequest)
                    .addComponent(btnCompleteRequest))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPharmResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmResultActionPerformed

    private void btnAcceptPharmRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptPharmRequestActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAvailablePharmRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a record.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAvailablePharmRequests.getModel();
            PharmacyRequest pharmacyRequest = (PharmacyRequest) model.getValueAt(selectedRowIndex, 0);

            
            
            pharmacyRequest.setEmployeeid(this.currentUser.getId());
            pharmacyRequest.setStatus("request-in-process");
            this.pharmacyRequestDaoImplementation.update(pharmacyRequest);
            populateAvailablePharmacyRequests();
            populateAcceptedPharmacyRequests();

        } catch (SQLException ex) {
            Logger.getLogger(PharmacyRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnAcceptPharmRequestActionPerformed

    private void btnUpdatePharmRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePharmRequestActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            int selectedRowIndex = tblAcceptedPharmRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a record.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tblAcceptedPharmRequests.getModel();
            PharmacyRequest pharmacyRequest = (PharmacyRequest) model.getValueAt(selectedRowIndex, 0);
            
            pharmacyRequest.setStatus("request-done");
            pharmacyRequest.setPharmacyRequest(txtPharmResult.getText());
            this.pharmacyRequestDaoImplementation.update(pharmacyRequest);
            populateAvailablePharmacyRequests();
            populateAcceptedPharmacyRequests();

        } catch (SQLException ex) {
            Logger.getLogger(PharmacyRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnUpdatePharmRequestActionPerformed

    void populateAvailablePharmacyRequests() {
        DefaultTableModel model = (DefaultTableModel) tblAvailablePharmRequests.getModel();
        model.setRowCount(0);
        try {
            for (PharmacyRequest pharmacyRequest : this.pharmacyRequestDaoImplementation.getPharmacyRequestsByStatus("drug-requested")) {

                if (pharmacyRequest.getNetwork().equals(this.currentOrganization.getLocation())) {
                    Object[] row = new Object[5];
                    row[0] = pharmacyRequest;
                    row[1] = pharmacyRequest.getPharmacyRequest();
                    row[2] = pharmacyRequest.getPharmacyResponse();
                    row[3] = pharmacyRequest.getStatus();
                    row[4] = pharmacyRequest.getPatientId();

                    model.addRow(row);
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(PharmacyRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void populateAcceptedPharmacyRequests() {
        DefaultTableModel model = (DefaultTableModel) tblAcceptedPharmRequests.getModel();
        model.setRowCount(0);
        try {
            for (PharmacyRequest pharmacyRequest : this.pharmacyRequestDaoImplementation.getPharmacyRequestsByPharmacyId(this.currentUser.getId())) {
                // -1 means doctor is not assigned yet and is available for picking up by a doctor
                if ("request-in-process".equals(pharmacyRequest.getStatus())) {
                    Object[] row = new Object[5];
                    row[0] = pharmacyRequest;
                    row[1] = pharmacyRequest.getPharmacyRequest();
                    row[2] = pharmacyRequest.getPharmacyResponse();
                    row[3] = pharmacyRequest.getStatus();
                    row[4] = pharmacyRequest.getPatientId();
                    model.addRow(row);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PharmacyRequestsMngt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptPharmRequest;
    private javax.swing.JButton btnCompleteRequest;
    private javax.swing.JButton btnUpdatePharmRequest;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPharmEmpId;
    private javax.swing.JLabel lblPharmEmpName;
    private javax.swing.JLabel lblPharmEmpPhone;
    private javax.swing.JLabel lblPharmacyEmployeeId;
    private javax.swing.JLabel lblPharmacyEmployeeName;
    private javax.swing.JLabel lblPharmacyEmployeePhone;
    private javax.swing.JTable tblAcceptedPharmRequests;
    private javax.swing.JTable tblAvailablePharmRequests;
    private javax.swing.JTextField txtPharmResult;
    // End of variables declaration//GEN-END:variables
}
